// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iulqpgvdmtlblfeuksub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bHFwZ3ZkbXRsYmxmZXVrc3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ1MDUsImV4cCI6MjA2NTQ3MDUwNX0.RWJ5cTIWfapWbsoClERQFrPvKhyIR4xtfAWBpOhJk6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);